/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ArchitectureRouteImport } from './routes/architecture'
import { Route as DashboardsRouteImport } from './routes/dashboards'
import { Route as DecisionRouteImport } from './routes/decision'
import { Route as EconomicsRouteImport } from './routes/economics'
import { Route as FloorRouteImport } from './routes/floor'
import { Route as GuardrailsRouteImport } from './routes/guardrails'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ArchitectureRoute = ArchitectureRouteImport.update({
  id: '/architecture',
  path: '/architecture',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardsRoute = DashboardsRouteImport.update({
  id: '/dashboards',
  path: '/dashboards',
  getParentRoute: () => rootRouteImport,
} as any)
const DecisionRoute = DecisionRouteImport.update({
  id: '/decision',
  path: '/decision',
  getParentRoute: () => rootRouteImport,
} as any)
const EconomicsRoute = EconomicsRouteImport.update({
  id: '/economics',
  path: '/economics',
  getParentRoute: () => rootRouteImport,
} as any)
const FloorRoute = FloorRouteImport.update({
  id: '/floor',
  path: '/floor',
  getParentRoute: () => rootRouteImport,
} as any)
const GuardrailsRoute = GuardrailsRouteImport.update({
  id: '/guardrails',
  path: '/guardrails',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/architecture': typeof ArchitectureRoute
  '/dashboards': typeof DashboardsRoute
  '/decision': typeof DecisionRoute
  '/economics': typeof EconomicsRoute
  '/floor': typeof FloorRoute
  '/guardrails': typeof GuardrailsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/architecture': typeof ArchitectureRoute
  '/dashboards': typeof DashboardsRoute
  '/decision': typeof DecisionRoute
  '/economics': typeof EconomicsRoute
  '/floor': typeof FloorRoute
  '/guardrails': typeof GuardrailsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/architecture': typeof ArchitectureRoute
  '/dashboards': typeof DashboardsRoute
  '/decision': typeof DecisionRoute
  '/economics': typeof EconomicsRoute
  '/floor': typeof FloorRoute
  '/guardrails': typeof GuardrailsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/architecture'
    | '/dashboards'
    | '/decision'
    | '/economics'
    | '/floor'
    | '/guardrails'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/architecture'
    | '/dashboards'
    | '/decision'
    | '/economics'
    | '/floor'
    | '/guardrails'
  id:
    | '__root__'
    | '/'
    | '/architecture'
    | '/dashboards'
    | '/decision'
    | '/economics'
    | '/floor'
    | '/guardrails'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ArchitectureRoute: typeof ArchitectureRoute
  DashboardsRoute: typeof DashboardsRoute
  DecisionRoute: typeof DecisionRoute
  EconomicsRoute: typeof EconomicsRoute
  FloorRoute: typeof FloorRoute
  GuardrailsRoute: typeof GuardrailsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/architecture': {
      id: '/architecture'
      path: '/architecture'
      fullPath: '/architecture'
      preLoaderRoute: typeof ArchitectureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboards': {
      id: '/dashboards'
      path: '/dashboards'
      fullPath: '/dashboards'
      preLoaderRoute: typeof DashboardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/decision': {
      id: '/decision'
      path: '/decision'
      fullPath: '/decision'
      preLoaderRoute: typeof DecisionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/economics': {
      id: '/economics'
      path: '/economics'
      fullPath: '/economics'
      preLoaderRoute: typeof EconomicsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/floor': {
      id: '/floor'
      path: '/floor'
      fullPath: '/floor'
      preLoaderRoute: typeof FloorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guardrails': {
      id: '/guardrails'
      path: '/guardrails'
      fullPath: '/guardrails'
      preLoaderRoute: typeof GuardrailsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ArchitectureRoute: ArchitectureRoute,
  DashboardsRoute: DashboardsRoute,
  DecisionRoute: DecisionRoute,
  EconomicsRoute: EconomicsRoute,
  FloorRoute: FloorRoute,
  GuardrailsRoute: GuardrailsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
